# define skill
classes = { "aran": {"fb": "Final Blow",
                     "bb": "Beyond Blade",
                     "ss": "Smash Swing",
                     "fa": "Final Attack",
                     "ht": "Hunter's Targeting",
                     "md": "Maha Domain",
                     "end": "end"},
            "evan": {"cm": "Circle of Mana",
                     "ce": "Circle of Earth",
                     "cw": "Circle of Wind",
                     "ds": "Dragon Spark",
                     "db": "Dragon Breath",
                     "mr": "Magical Residuue",
                     "end": "end"},
            "mercedes": {"ir": "Ishtar’s Ring",
                         "ss": "Stunning Strikes",
                         "le": "Lightning Edge",
                         "sr": "Spikes Royale",
                         "we": "Wrath of Enlil",
                         "lt": "Leaf Tornado",
                         "rr": "Rising Rush",
                         "us": "Unicorn Spikes",
                         "ek": "Elemental Knight",
                         "end": "end"},
            "phantom": {"i1": "Impeccable Memory I",
                        "i2": "Impeccable Memory II",
                        "i3": "Impeccable Memory III",
                        "i4": "Impeccable Memory IV",
                        "cf": "Carte Rose Finale",
                        "tp": "Tempest",
                        "ma": "Mille Aiguilles",
                        "cb": "Carte Blanc",
                        "ex": "extra",
                        "end": "end"},
            "darkknight": {"be": "Beholder",
                    "di": "Dark Impale",
                    "ds": "Dark Synthesis",
                    "fa": "Final Attack",
                    "la": "Leap Attack",
                    "gd": "Gungnir's Descent",
                    "end": "end"},
            "hero": {"rb": "Raging Blow",
                     "va": "Valhalla",
                     "fa": "Final Attack",
                     "in": "Incising",
                     "ak": "Aura Katara",
                     "ru": "Rage Uprising",
                     "end": "end"},

            "bishop": {"ar": "Angel Ray",
                       "bb": "Big Bang",
                       "ba": "Bahamut",
                       "hd": "Heaven's Door",
                       "ge": "Genesis",
                       "he": "Heal",
                       "end": "end"},
            "icelightning": {"ts": "Thunder Spear",
                             "ls": "Lightning Sphere",
                             "cl": "Chain Lightning",
                             "fo": "Frozen Orb",
                             "bl": "Blizzard",
                             "el": "Elquines",
                             "end": "end"},
            "nightlord": {"ma": "Mark of Assassin",
                          "qs": "Quad Star",
                          "sd": "Showdown",
                          "df": "Dark Flare",
                          "sr": "Sudden Raid",
                          "fs": "Four Seasons",
                          "end": "end"},
            "cannonmaster": {"cb": "Cannon Barrage",
                             "ck": "Cannon Bazooka",
                             "rc": "Rolling Cannon Rainbow",
                             "mf": "Monkey Fury",
                             "mm": "Monkey Milita",
                             "ns": "Nautilus Strike",
                             "end": "end"},
            "viper": {"cb": "Corkscrew Blow",
                      "oc": "Octopunch",
                      "hb": "Hook Bomber",
                      "es": "Enchances Sea Serpent Burst",
                      "ss": "Sea Serpent Burst",
                      "ns": "Nautilus Strike",
                      "end": "end"},
            "adele": {"di": "Divide",
                      "or": "Order",
                      "cr": "Creation",
                      "te": "Territory",
                      "wo": "Wonder",
                      "bl": "Blossom",
                      "end": "end"},
            "hayato":{"rs": "Rai Sanrenzan",
                      "or": "Falcon Honor",
                      "fh": "Sudden Strike",
                      "sh": "Shinsoku",
                      "ir": "Iagiri No Rai",
                      "hs": "Hundred Strike",
                      "end": "end"},
            "kanna": {"di": "Shikigami",
                      "or": "Tengu Strike",
                      "cr": "Vanquisher's Charm",
                      "te": "Spirit Coral",
                      "wo": "Celestial Fury",
                      "bl": "Kishin",
                      "cy": "Clay Yaksha",
                      "end": "end"}
            }


