# define skill
job = { "aran": {"fb": "Final Blow",
                 "bb": "Beyond Blade",
                 "ss": "Smash Swing",
                 "fa": "Final Attack",
                 "ht": "Hunter's Targeting",
                 "md": "Maha Domain",
                 "end": "end"},
   "mercedes" : {"ir": "Ishtar’s Ring",
                 "ss": "Stunning Strikes",
                 "le": "Lightning Edge",
                 "sr": "Spikes Royale",
                 "we": "Wrath of Enlil",
                 "lt": "Leaf Tornado",
                 "rr": "Rising Rush",
                 "us": "Unicorn Spikes",
                 "ek": "Elemental Knight",
                 "end": "end"},
   "phantom" :  {"i1": "Impeccable Memory I",
                 "i2": "Impeccable Memory II",
                 "i3": "Impeccable Memory III",
                 "i4": "Impeccable Memory IV",
                 "cf": "Carte Rose Finale",
                 "tp": "Tempest",
                 "ma": "Mille Aiguilles",
                 "cb": "Carte Blanc",
                 "ex": "extra",
                 "end": "end"},
   "nightlord": {"ma": "Mark of Assassin",
                 "qs": "Quad Star",
                 "sd": "Showdown",
                 "df": "Dark Flare",
                 "sr": "Sudden Raid",
                 "fs": "Four Seasons",
                 "end": "end"},
          "i/l":{"ts": "Thunder Spear",
                 "ls": "Lightning Sphere",
                 "cl": "Chain Lightning",
                 "fo": "Frozen Orb",
                 "bl": "Blizzard",
                 "el": "Elquines",
                 "end": "end"},
     "bishop" : {"ar": "Angel Ray",
                 "bb": "Big Bang",
                 "ba": "Bahamut",
                 "hd": "Heaven's Door",
                 "ge": "Genesis",
                 "he": "Heal",
                 "end": "end"},
       "hero" : {"rb": "Raging Blow",
                 "va": "Valhalla",
                 "fa": "Final Attack",
                 "in": "Incising",
                 "ak": "Aura Katara",
                 "ru": "Rage Uprising",
                 "end": "end"},
       "adele" :{"di": "Divide",
                 "or": "Order",
                 "cr": "Creation",
                 "te": "Territory",
                 "wo": "Wonder",
                 "bl": "Blossom",
                 "end": "end"}
        }


